connection rightech
address dev.rightech.io:1883
clientid <68fcd4406dffe6c39bbb2a88>
try_private false
start_type automatic

topic /devices/wb-msw-v3_64/controls/Temperature both
topic /devices/wb-msw-v3_64/controls/Humidity both
topic /devices/wb-gpio/controls/EXT1_IN2 both
topic "/devices/wb-led_39/controls/RGB Palette" both
